version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: modsen-2025-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./meetups
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: modsen-2025-meetups
    environment:
      JWT_REFRESH_SECRET: "JWT_REFRESH_SECRET"
      JWT_REFRESH_LIFETIME: "720s"
      JWT_ACCESS_SECRET: "JWT_ACCESS_SECRET"
      JWT_ACCESS_LIFETIME: "360s"
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
    depends_on:
      - postgres

volumes:
  postgres_data:
